name: default

on:
  push:

jobs:
  provisioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cat<<EOE > .env
          CURRENT_ENV_NAME=test
          EOE
      - run: |
          echo "UID=$(id -u)" >> .env
          echo "GID=$(id -g)" >> .env
      - name: set up ssh credentials for testing
        run: |
          mkdir -p ${HOME}/.ssh/
          ssh-keygen -C '' -f ${HOME}/.ssh/id_rsa -N '' -q
      - run: docker-compose build
      - run: docker-compose up
      - run: docker-compose down -v
